### ISSUE TITLE
configuring centroid-rna package

### ISSUE THREAD

**Issue by clarajanae** [satoken/centroid-rna-package#2]
Hey, I am pretty new at all this and am having a bit of trouble configuring the centroid-rna package and get an error like this

Claras-MacBook-Pro:centroid-rna-package-master clarawilliams$ ./configure --with-vienna-rna= /usr/local/share/ViennaRNA/
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: /usr/local/share/ViennaRNA/
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for /usr/local/share/ViennaRNA/-g++... no
checking for /usr/local/share/ViennaRNA/-c++... no
checking for /usr/local/share/ViennaRNA/-gpp... no
checking for /usr/local/share/ViennaRNA/-aCC... no
checking for /usr/local/share/ViennaRNA/-CC... no
checking for /usr/local/share/ViennaRNA/-cxx... no
checking for /usr/local/share/ViennaRNA/-cc++... no
checking for /usr/local/share/ViennaRNA/-cl.exe... no
checking for /usr/local/share/ViennaRNA/-FCC... no
checking for /usr/local/share/ViennaRNA/-KCC... no
checking for /usr/local/share/ViennaRNA/-RCC... no
checking for /usr/local/share/ViennaRNA/-xlC_r... no
checking for /usr/local/share/ViennaRNA/-xlC... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for /usr/local/share/ViennaRNA/-gcc... no
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking for /usr/local/share/ViennaRNA/-ranlib... no
checking for ranlib... ranlib
checking whether ln -s works... yes
checking for gawk... (cached) awk
checking for a sed that does not truncate output... /usr/bin/sed
checking for /usr/local/share/ViennaRNA/-ar... no
checking for /usr/local/share/ViennaRNA/-lib... no
checking for /usr/local/share/ViennaRNA/-link... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... /usr/local/share/ViennaRNA/
configure: error: invalid value of canonical build

**Comment by satoken** [comment]
Thank you for using centroid_fold!

I found a typo at running the configure script.

> ./configure --with-vienna-rna= /usr/local/share/ViennaRNA/

A space between '--with-vienna-rna='  and '/usr/local/share/ViennaRNA/' causes a error.
And, could you make sure that the Vienna RNA is installed at /usr/lcoal/share/ViennaRNA instead of /usr/local?

Thanks,
