### ISSUE TITLE
CentroidFold prediction is just dots

### ISSUE THREAD

**Issue by calmeidaa** [satoken/centroid-rna-package#3]
Hi CentroidFold team!

I am running CentroidFold, with default parameters, for 200000 sequences of length 52. 
In about 25% of them, CentroidFold predicts:
....................................................  (g=1,th=0.5,e=*anything*)
My question is if this means that CentroidFold actually predicts that this sequence does not have a secondary structure, or if this means CentroidFold for some reason failed in calculating a secondary structure for these specific sequences.

Thank you in advance for your help,
Catarina

**Comment by satoken** [comment]
Thank you for using CetroidFold!

I guess g is too small for such sequences. Please try to give '-g -1' option, which tries various values from 2^-5 to 2^10.

Best regards,

Kengo

**Comment by calmeidaa** [comment]
Thank you for your answer Kengo!
I have followed your recommendation, however now I have 17 secondary structures associated with each sequence, and no idea which one to choose.
Can you help me please?

# 1 #
As I understand from centroidfold's paper, gamma is the parameter that counter balances the sensitivity and the positive predicted value of the predicted secondary structures. 
A higher gamma will have better sensitivities but smaller PPVs. A lower gamma will have lesser sensitivities and higher PPVs.
So which is the ideal gamma? Do I sacrifice sensitivity or do I sacrifice assurance on my secondary structure predictions?
# 2 #
While reading Hamada, 2009, "Prediction of RNA secondary structure using generalized centroid estimators", I understood from your results that you seem to have proven that the combination of the McCaskill model, with gamma = 1, is the combo that best predicts secondary structure - did I understand this right?

If so, and going back to my original issue, shouldn't I just consider gamma = 1 for my sequences?

Thank you again in advance for your help!
All the best,
C

**Comment by satoken** [comment]
It is difficult to find the optimal gamma for each sequence. Although our paper
showed the best accuracy was achieved in gamma=1 for the McCaskill model, this
is the *average* result in our benchmark dataset.

One solution to choose gamma is to use the pseudo-expected accuracy, which has
been proposed in our another paper https://www.ncbi.nlm.nih.gov/pubmed/21118522

To do that, we provide an option "--ea" to choose the best gamma that maximizes
pseudo-expected accuracy from given gammas. This is an example:

    $ centroid_fold -g -1 --ea 0 a.fa
    >RF00008_B
    AAAAGUCUGGGCUAAGCCCACUGAUGAGCCGCUGAAAUGCGGCGAAACUUUUG
    ((((((.(((((...))))).......(((((......)))))...)))))). (g=2,th=0.333333,e=-11.62)
    .((((...((((...))))........(((((......)))))....)))).. (g=0.5,th=0.666667,e=-11.17)
    ((((((((((((...))))).......(((((......))))))..)))))). (g=6,th=0.142857,e=-10.67)
    ((((((((((((...)))))(....).(((((......))))))..)))))). (g=32,th=0.030303,e=-9.06)
    ...((...((((...))))........(((((......)))))....)).... (g=0.25,th=0.8,e=-9.79)
    ((((((((((((...)))))(....).((((((...).))))))..)))))). (g=256,th=0.00389105,e=-5.93)
    ........(((.....)))........(((((......))))).......... (g=0.125,th=0.888889,e=-9.25)
    ........(((.....))).................................. (g=0.0625,th=0.941176,e=-2.84)
    .........((.....))................................... (g=0.03125,th=0.969697,e=-0.27)

In this example, we guess gamma=2 is the best.

Best regards,

Kengo
