### ISSUE TITLE
Not working with external boost lib

### ISSUE THREAD

**Issue by SchwarzMarek** [satoken/centroid-rna-package#5]
Hello,
I've problems to get centroid_homfold working with external library.

Short story:
I'm on Ubuntu 14.04 (default boost version is too low and cant compile).
So I've installed miniconda and obtained boost 1.57.0, compiled but execution fails with: 
`./centroid_homfold: error while loading shared libraries: libboost_program_options.so.1.57.0: cannot open shared object file: No such file or directory`

Long story:
Missing boost lib in correct version for Ubuntu 14.04. Conda provides easy alternative installs of several boost versions. Also I have vienna-rna package installed with conda.
I've installed 2 versions of boost: 1.65.1 and 1.57.0-4, and vienna-rna 2.3.5 to "$HOME/miniconda2"

running configure:
```
BOOSTV is either: boost-1.57.0-4 or llibboost-1.65.1-habcd387_4.

./configure --with-boost="$HOME/pkgs/BOOSTV" --with-vienna-rna="$HOME/miniconda2/pkgs/viennarna-2.3.5-0"
```
Configure runs successfully in both versions.

Make fails for boost 1.65.1 and compiles centroid for boost 1.57.0 (see report files)

Then I've tried to execute `centroid_homfold` program in src directory and execution fails with:
`./centroid_homfold: error while loading shared libraries: libboost_program_options.so.1.57.0: cannot open shared object file: No such file or directory`

Running make install, including boost lib to path, does not help. Including boost lib to PATH prior to installation does not get through `./configure`. Defining `$BOOST_ROOT` does not help either.

After running `strace` it appears to me (to my poor understanding) that compiled `centroid_homfold` does not look for libboost_program_options in the path specified but rather in standard installation path. (strace output included)

Could you advice how to correctly compile with boostlib installed with miniconda?
Thanks
Best Regards
Marek Schwarz

[centroid_compile_boost_1.57.0-4.txt](https://github.com/satoken/centroid-rna-package/files/1914500/centroid_compile_boost_1.57.0-4.txt)
[centroid_compile_boost_1.65.1.txt](https://github.com/satoken/centroid-rna-package/files/1914501/centroid_compile_boost_1.65.1.txt)
[compiled_centroid_error.txt](https://github.com/satoken/centroid-rna-package/files/1914502/compiled_centroid_error.txt)
[compiled_centroid_strace_output.txt](https://github.com/satoken/centroid-rna-package/files/1914503/compiled_centroid_strace_output.txt)

**Comment by satoken** [comment]
Thank you for using centroid RNA package.

Please check LD_LIBRARY_PATH environment variable.
Add the path that contains libboost_program_options.so.1.57.0 (probably "$HOME/pkgs/BOOSTV/lib") to LD_LIBRARY_PATH.

Or, please use the precompiled binary:
https://github.com/satoken/centroid-rna-package/releases/tag/v0.0.15

Best regards,

Kengo

**Comment by SchwarzMarek** [comment]
Thank you, the pre-compiled binary works like a charm. I wasn't aware of it.
Best regards
